### ISSUE TITLE
Slab leak in Android Kernel

### ISSUE THREAD

**Issue by grassead** [boundarydevices/linux-imx6#57] opened 2020-04-14 19:32 UTC
Hi,

When trying Android 8 on a Sabrelite, I encounter an issue (located in the kernel (4.9.88 - commit 2324d068)).

The "Slab memory" is leaking when the graphics system (SurfaceFlinger) does composition.

For example, I wrote an application that pop a Toast as fast as possible.

Before running the test, cat /proc/meminfo gives:
Slab:              42092 kB
SReclaimable:      15076 kB
SUnreclaim:        27016 kB

After Running the application for 10-15 minutes:
Slab:              78960 kB
SReclaimable:      14828 kB
SUnreclaim:        64132 kB

After killing the application:
Slab:              80956 kB
SReclaimable:      14960 kB
SUnreclaim:        65996 kB

The "SUnreclaim" is not freed.

Could you please help me to fix this issue.

Thanks,

**Comment by gibsson** [comment] 2020-04-16 12:13
Hi Adrien,

Thanks for this report. We've seen issues with Android 8 indeed.

We'll look into it as soon as possible but we have many ongoing projects at this time.

Regards,
Gary

**Comment by JeansHH** [comment] 2020-08-12 10:40
+1 Are there any updates?

**Comment by ep-skolberg** [comment] 2020-08-13 06:30
+1 
for us, this issue blocking an upgrade to Android 8

**Comment by gibsson** [comment] 2020-08-17 08:04
Sorry we haven't had a chance to look at it yet.
We'll keep you posted as soon as we have an update.

**Comment by JeansHH** [comment] 2020-08-20 06:58
I looked into the code and it looks like the fences created in viv_fence_create (os/linux/kernel/gc_hal_kernel_sync.c) are never released. Maybe I am wrong or this is not relevant. But if this is the problem, is there a way to release the fence?

**Comment by gibsson** [comment] 2020-08-25 09:02
Another update:
- @JeansHH I confirm that there is some leak in the fence that it is unfortunately not the main issue I'm afraid.
Enabling KMEMLEAK showed the fence leak:
```
unreferenced object 0xd3e19080 (size 128):
  comm "surfaceflinger", pid 301, jiffies 4294948055 (age 102.340s)
  hex dump (first 32 bytes):
    01 00 00 00 74 7b 6e c1 00 00 00 00 00 00 00 00  ....t{n.........
    90 90 e1 d3 90 90 e1 d3 c0 90 e1 d3 00 00 00 00  ................
  backtrace:
    [<c0291a58>] kmem_cache_alloc_trace+0x1a4/0x2b0
    [<c09945ac>] viv_fence_create+0x3c/0x1ec
    [<c0962560>] gckOS_CreateNativeFence+0x7c/0x11c
    [<c096cfe8>] gckKERNEL_Dispatch+0x468/0x12d4
    [<c096e124>] gckDEVICE_Dispatch+0x2d0/0x2d4
    [<c0966614>] drv_ioctl+0x140/0x320
    [<c02b3c9c>] do_vfs_ioctl+0xc0/0x9c4
    [<c02b461c>] SyS_ioctl+0x7c/0x8c
    [<c01088c0>] ret_fast_syscall+0x0/0x48
    [<ffffffff>] 0xffffffff
```
However after updating some part of the driver to p9, that fence leak is gone but the main leak isn't.
See my patch here if you want to give it a try:
https://gist.github.com/gibsson/45921590256a95c5b868e37387e1909d
- I confirm that this issue is gone with the p9.0.0_2.2.0_ga release, if you're interested, our partner Kynetics does have a release for Nitrogen platforms: https://www.kynetics.com/android-bsp/boundary-devices
- I tried backporting p9 Vivante binaries to o8 but it's more difficult than expected as:
 1- memory allocation mechanism changed
 2- new binaries depend on libraries that don't exist in i.MX Oreo (libdrm_vivante, libdrm_android)

**Comment by JeansHH** [comment] 2020-08-26 06:14
@gibsson Thank you such much for your effort. I really appreciate it. I will give your patch a try.

I will talk to my colleagues checking if we can migrate to android 9. Do you keep working on the issue?

Once again: Thank you such much!

**Comment by JeansHH** [comment] 2020-08-26 13:29
The behaviour is much better with this patch

**Comment by RomainNaour** [comment] 2020-09-23 13:15
Hello @gibsson,

I just tested with the latest kernel for Android 8 (boundary-imx-o8.0.0_1.0.0-ga branch)
https://github.com/boundarydevices/linux-imx6/commit/5f751704211d4753d7ef6676d49622eae306256c
But the but is still present.

In the end, the nxp firmware o8.0.0_1.0.0-ga is buggy... what about o8.1.0_1.3.0 firmware ?
Can we use them instead ?

Best regards,
Romain

**Comment by gibsson** [comment] 2020-09-23 13:21
Hi Romain,

Yes, there were 2 leaks before, that patch only fixes 1 of them (the one in the kernel).
The issue has been reproduced on NXP EVK platform with their prebuilt images so clearly comes from NXP release.
Not sure about the other Oreo releases, as none of them were GA for i.MX6Q.
To be honest I've tried porting the libraries from o8.1.0_1.3.0 to o8.0.0 but it's not as straightforward as it sounds since NXP changed its graphics libs to depend on libdrm which wasn't the case in o8.0.0.
All I can say is that the issue doesn't occur on Nougat nor Pie so we now strongly recommend not to use Oreo.

Regards,
Gary

**Comment by RomainNaour** [comment] 2020-09-23 15:07
Hi Gary,

Thank you for your quick reply!
What about convincing NXP to do a fix release of these o8.0.0_1.0.0-ga firmware ?

Best regards,
Romain

**Comment by RomainNaour** [comment] 2020-09-23 15:16
Hi Gary,

No problem, my customer asked me to ask this question.
We'll try on our side as well.

Thanks,
Romain

**Comment by RomainNaour** [comment] 2020-09-24 07:25
Hi Gary,

Here is the link to the NXP community forum where the request has been posted yesterday:
https://community.nxp.com/t5/i-MX-Graphics/Memory-leak-spotted-on-i-MX6-with-Android-8/m-p/1157843#M15

Best regards,
Romain

**Comment by gibsson** [comment] 2020-09-24 07:32
Hi Romain,
Thanks for creating that post. I've replied making sure to mention it was reproduced on SabreSD, otherwise the answer will be "it's because you don't use NXP platform".
Now, I think it would be best for you to share the apk there as well as repro steps and procedure to see the memory leak increase.
Thanks,
Gary

**Comment by RomainNaour** [comment] 2020-09-24 09:26
Hi Gary,
Done:
https://community.nxp.com/t5/i-MX-Graphics/Memory-leak-spotted-on-i-MX6-with-Android-8/m-p/1158567/highlight/true#M17

Best regards,
Romain

**Comment by RomainNaour** [comment] 2020-09-24 14:27
Hello @JeansHH  @ep-skolberg,

Can you add a comment about your issue on the NXP forum?
It would help to convince NXP to take a look at our issue.

Thanks,
Romain

**Comment by JeansHH** [comment] 2020-09-25 10:11
done

**Comment by RomainNaour** [comment] 2020-10-08 15:44
Hello,

NXP did a test on Pixel mobile and reproduced the issue using our app.

https://community.nxp.com/t5/i-MX-Graphics/Memory-leak-spotted-on-i-MX6-with-Android-8/m-p/1161467/highlight/true#M21

So it's not clear if it's really a imx6 issue or not.

**Comment by gibsson** [comment] 2020-10-08 15:48
Has anyone other than NXP been able to verify that claim?

**Comment by RomainNaour** [comment] 2020-10-08 16:20
Not yet, I was looking at testing Android 8 on a potato board or a Rasperry-pi.

https://libre.computer/2018/09/27/android-release-for-tritium-and-le-potato

If the issue is really not related to NXP firmware but Android AOSP part, the issue should be reproducible with an emulator ?

Thanks again Gary!

**Comment by RomainNaour** [comment] 2020-10-13 22:07
Hi Gary,

I tried to reproduce the leak using two different board: a RasperryPi 3 with LineageOS image (15.1 based on Android 8.0 but with a kernel 4.4), a Le Potato from the link above (Android 8.0.0, kernel 4.9.61).

I'm unable to reproduce the issue so far, even on Le Potato board using an Android image very close to the image provided by BoundaryDevice for the Sabrelite board.

I'm not sure how NXP is able to reproduce the issue on a Android Pixel phone...

Best regards,
Romain

**Comment by gibsson** [comment] 2020-10-14 06:53
Hi,
Please share those findings on the community forum. To be honest, I don't believe the testing done on Pixel was correct.
Regards

**Comment by grassead** [comment] 2020-10-17 19:10
Hi,

I reproduced this issue on my Pixel 2 (to a lesser extent) on android-8.0.0_r34 (the last aosp release for Pixel 2) running on kernel 4.4.56-g594d847d09a1.

18h12
walleye:/ # cat /proc/meminfo
Slab:             135940 kB
SReclaimable:      47344 kB
SUnreclaim:        88596 kB

20h24
walleye:/ # cat /proc/meminfo
Slab:             137952 kB
SReclaimable:      47604 kB
SUnreclaim:        90348 kB

Thanks,

**Comment by gibsson** [comment] 2020-11-13 16:48
I am closing this issue as the kernel doesn't have any leak any longer.
Also, it has been proven that an update of Vivante libraries can fix the issue.

**Closed by gibsson** 2020-11-13 16:48 UTC
